DOMAIN: 'http://51.250.106.229'

NEWS_PARSER: 'http://185.209.29.54:3001/api/v1?url='
SEARX_URL: 'http://127.0.0.1:8888/search'

ADMIN_USERNAME: 'admin'
ADMIN_PASSWORD: 'admin'

SECRET_KEY: 'bad_key'
MODEL_PATH: '/home/user/moscowcityhack-backend-api/d2v.model'